name: Lint Check
on:
  push:
    branches: [main, master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn install
      - name: Run ESLint
        run: yarn lint
